
##spring.application.name=identity-service
server:
  port: 8080
  servlet:
    context-path: /bej3

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/new_bej_sp3"
    username: root
    password: root

    #    url: jdbc:mysql://trolley.proxy.rlwy.net:10577/railway?useSSL=false&serverTimezone=UTC
    #    username: root
    #    password: ApyPKrVxeduoQRGCKszrRQEdygTbvyUG
    #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

jwt:
  signerKey: "7bZydhCMPlM7eKuKjxy1gIhbtMo7hTPNvYJr2FguJZtvxpeQ21K3MjP90WjNtYLO"